#define mix lerp
#define vec float
#define vec2 float2
#define vec3 float3
#define vec4 float4
#define iTime Time
#define fract frac

float opSmoothUnion(float d1, float d2, float k)
{
    float h = clamp(0.5 + 0.5 * (d2 - d1) / k, 0.0, 1.0);
    return mix(d2, d1, h) - k * h * (1.0 - h);
}

float sdSphere(vec3 p, float s)
{
    return length(p) - s;
}

float map(vec3 p, float Time)
{
    float d = 2.0;
    for (int i = 0; i < 16; i++) {
        float fi = float(i);
        float time = Time * (fract(fi * 412.531 + 0.513) - 0.5) * 2.0;
        d = opSmoothUnion(
            sdSphere(p + sin(time + fi * vec3(52.5126, 64.62744, 632.25)) * vec3(2.0, 2.0, 0.8), mix(0.5, 1.0, fract(fi * 412.531 + 0.5124))),
            d,
            0.4
        );
    }
    return d;
}

vec3 calcNormal(vec3 p, float Time)
{
    float h = 1e-5;
    vec2 k = vec2(1, -1);
    return normalize(
        k.xyy * map(p + k.xyy * h, Time) +
        k.yyx * map(p + k.yyx * h, Time) +
        k.yxy * map(p + k.yxy * h, Time) +
        k.xxx * map(p + k.xxx * h, Time)
    );
}

float4 MainRaymarch(float2 fragCoord, float2 Resolution, float Time)
{
    vec2 uv = fragCoord / Resolution;
    vec3 rayOri = vec3((uv - 0.5) * vec2(Resolution.x / Resolution.y, 1.0) * 6.0, 3.0);
    vec3 rayDir = vec3(0.0, 0.0, -1.0);

    float depth = 0.0;
    vec3 p;

    for (int i = 0; i < 64; i++) {
        p = rayOri + rayDir * depth;
        float dist = map(p, Time);
        depth += dist;
        if (dist < 1e-6) {
            break;
        }
    }

    depth = min(6.0, depth);
    vec3 n = calcNormal(p, Time);
    float b = max(0.0, dot(n, vec3(0.577, 0.577, 0.577)));
    vec3 col = (0.5 + 0.5 * cos((b + Time * 3.0) + uv.xyx * 2.0 + vec3(0, 2, 4))) * (0.85 + b * 0.35);
    col *= exp(-depth * 0.15);

    return float4(col, 1.0 - (depth - 0.5) / 2.0);
}