;METADATA=(Diff=true, UseCommands=true)
[/Script/MessageTags.MessageTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+MessageTagList=(Tag="A.B.C",DevComment="",Parameters=((Name="Param",Type="String"),(Name="Param_0",Type="String")),ResponseTypes=)
+MessageTagList=(Tag="A.B.D",DevComment="",Parameters=((Name="Description",Type="Text"),(Name="Name",Type="Text")),ResponseTypes=)

