;METADATA=(Diff=true, UseCommands=true)
[/Script/MessageTags.MessageTagsList]
MessageTagList=(Tag="GameState.OnPostStartPlay",DevComment="CodeGen",Parameters=((Name="Param",Type="World")),ResponseTypes=)
MessageTagList=(Tag="GMP.OnPlayerPossessed",DevComment="CodeGen",Parameters=((Name="Param",Type="Pawn")),ResponseTypes=)
MessageTagList=(Tag="GMP.OnPostWorldCleanup",DevComment="CodeGen",Parameters=((Name="Param",Type="World"),(Name="Param_0",Type="bool"),(Name="Param_1",Type="bool")),ResponseTypes=)
MessageTagList=(Tag="GMP.OnPostWorldInitialization",DevComment="CodeGen",Parameters=((Name="Param",Type="World")),ResponseTypes=)
MessageTagList=(Tag="GMP.OnPreWorldInitialization",DevComment="CodeGen",Parameters=((Name="Param",Type="World")),ResponseTypes=)
MessageTagList=(Tag="GMP.OnWorldBeginPlay",DevComment="CodeGen",Parameters=((Name="Param",Type="World")),ResponseTypes=)
MessageTagList=(Tag="GMP.OnWorldBeginPlayNextTick",DevComment="CodeGen",Parameters=((Name="Param",Type="World")),ResponseTypes=)
MessageTagList=(Tag="GMP.OnWorldBeginTearDown",DevComment="CodeGen",Parameters=((Name="Param",Type="World")),ResponseTypes=)
MessageTagList=(Tag="GMP.OnWorldCleanup",DevComment="CodeGen",Parameters=((Name="Param",Type="World"),(Name="Param_0",Type="bool"),(Name="Param_1",Type="bool")),ResponseTypes=)
MessageTagList=(Tag="GMP.OnWorldInitializedActors",DevComment="CodeGen",Parameters=((Name="Param",Type="World")),ResponseTypes=)

